export const LOGIN_REQUEST_ADMIN = "LOGIN_REQUEST_ADMIN";
export const LOGIN_SUCCESS_ADMIN = "LOGIN_SUCCESS_ADMIN";
export const LOGIN_FAIL_ADMIN = "LOGIN_FAIL_ADMIN";

export const REGISTER_REQUEST_ADMIN = "REGISTER_REQUEST_ADMIN";
export const REGISTER_SUCCESS_ADMIN = "REGISTER_SUCCESS_ADMIN";
export const REGISTER_FAIL_ADMIN = "REGISTER_FAIL_ADMIN";

export const LOAD_REQUEST_ADMIN= "LOAD_REQUEST_ADMIN";
export const LOAD_SUCCESS_ADMIN = "LOAD_SUCCESS_ADMIN";
export const LOAD_FAIL_ADMIN = "LOAD_FAIL_ADMIN";

export const LOGOUT_SUCCESS_ADMIN = "LOGOUT_SUCCESS_ADMIN";
export const LOGOUT_FAIL_ADMIN = "LOGOUT_FAIL_ADMIN";

export const CLEAR_ERRORS = "CLEAR_ERRORS";