export const LOGIN_REQUEST_STUDENT = "LOGIN_REQUEST_STUDENT";
export const LOGIN_SUCCESS_STUDENT = "LOGIN_SUCCESS_STUDENT";
export const LOGIN_FAIL_STUDENT = "LOGIN_FAIL_STUDENT";

export const REGISTER_REQUEST_STUDENT = "REGISTER_REQUEST_STUDENT";
export const REGISTER_SUCCESS_STUDENT = "REGISTER_SUCCESS_STUDENT";
export const REGISTER_FAIL_STUDENT = "REGISTER_FAIL_STUDENT";

export const LOAD_REQUEST_STUDENT= "LOAD_REQUEST_STUDENT";
export const LOAD_SUCCESS_STUDENT = "LOAD_SUCCESS_STUDENT";
export const LOAD_FAIL_STUDENT = "LOAD_FAIL_STUDENT";

export const LOGOUT_SUCCESS_STUDENT = "LOGOUT_SUCCESS_STUDENT";
export const LOGOUT_FAIL_STUDENT = "LOGOUT_FAIL_STUDENT";

export const CLEAR_ERRORS = "CLEAR_ERRORS";