export const LOGIN_REQUEST_Teacher = "LOGIN_REQUEST_TEACHER";
export const LOGIN_SUCCESS_TEACHER = "LOGIN_SUCCESS_TEACHER";
export const LOGIN_FAIL_TEACHER = "LOGIN_FAIL_TEACHER";

export const REGISTER_REQUEST_TEACHER = "REGISTER_REQUEST_TEACHER";
export const REGISTER_SUCCESS_TEACHER = "REGISTER_SUCCESS_TEACHER";
export const REGISTER_FAIL_TEACHER = "REGISTER_FAIL_TEACHER";

export const LOAD_REQUEST_TEACHER= "LOAD_REQUEST_TEACHER";
export const LOAD_SUCCESS_TEACHER = "LOAD_SUCCESS_TEACHER";
export const LOAD_FAIL_TEACHER = "LOAD_FAIL_TEACHER";

export const LOGOUT_SUCCESS_TEACHER = "LOGOUT_SUCCESS_TEACHER";
export const LOGOUT_FAIL_TEACHER = "LOGOUT_FAIL_TEACHER";

export const CLEAR_ERRORS = "CLEAR_ERRORS";